language: java
jdk:
- oraclejdk8
services:
- postgresql
before_install:
- psql -c "create user simplevote with password 'asdf'" -U postgres
- psql -c "create database simplevote with owner simplevote" -U postgres
- cd service
after_success:
- cd ..
- ./deploy.sh
addons:
  postgresql: '9.3'
  apt:
    packages:
    - sshpass
