language: java
jdk:
- oraclejdk8
services:
- postgresql
before_install:
- psql -c "create user simplevote with password 'asdf'" -U postgres
- psql -c "create database simplevote with owner simplevote" -U postgres
- cd ui; npm i -g @angular/cli; yarn; ng build --prod --aot;
- cp -R dist/ ../service/src/main/resources
- cd ../service
addons:
  postgresql: '9.3'
  apt:
    packages:
    - sshpass
deploy:
  provider: releases
  api_key:
    secure: Wo7pxouj46DYMvweqnBfVVJJ+hNoUAJXFKESwREpC4UkDIvOWN4+2cwJjKlYTP/+6M8fYBMdS86fglO+Onv3kaHDC/DDFzGNvtKo9+eyuSuSwXwqXyCLEVa4BtnDl3gIAby6Q7JBHAdLZ5evMtx/AzWK1hTGaddLggo5Et1zvzWmvu0pX+Ej4yoAITbpRzO5VPufMQ95lsCPauED7B4J2KuW2IJCMlqHbzlVgqmGHaTUUVSHlRWoBKOKE2hBsZu5k/M2sHTEGOcvosBCqkB/R9ICWgDLIbNwmoXxM2CKqgziPnZPhnl6TNBFuKuwJQuVBBvovNbVP54SiKTiTywKJeI1u18J/KaV1Cy3RxI8xQsU6tu1bWvPKfGpyJFXoa1o9X6Dwql6TPTL0j2I4WfKEl7ht2fpa68VTyvm8+NYJr1Bzel6DFrWSyqC2I4jKKzIITeZRKgTpvtfgjXIhcCWWp/ZZwyksSBsezL/uEcd/wkzMkNm2+4BACb9kbF1IFJBAWXzr9kTb7w4UlXlhmWZ+WDOOz59oEpcGZa8ehJO1+yHujQMBTABRk4o0aVUKlOgzqr96/uvIyLpKV2tDgBaPbUp/spf/EhqnfP9o+ZKcw2rwXxVla3ObnxA9q4xkf512jfxgsjXrMammCnYY3mqkqhDzp3XYY1P4cm1NHhUzjs=
  file:
    - target/simplevote.jar
  skip_cleanup: true
  on:
    repo: dessalines/simple-vote
    tags: true
before_deploy:
- echo $PWD
after_deploy:
- cd ..
- ./deploy.sh
